# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d85ea7d7025c8697a66e57ce8c2baf06"
name = "CU Bubble Tea Shop Agent"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_files,write_files,read_publications,write_publications"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
