# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d85ea7d7025c8697a66e57ce8c2baf06"
name = "CU Bubble Tea Shop Agent"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_files,write_files,read_publications,write_publications,read_orders,write_orders,read_customers,write_customers,read_draft_orders,write_draft_orders,read_discounts,write_discounts,read_price_rules,write_price_rules,read_themes,write_themes,read_content,write_content,read_translations,write_translations,read_locales,write_locales,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_marketing_events,write_marketing_events,read_locations,read_reports,read_shipping,read_fulfillments,write_fulfillments,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
